#!/bin/sh
umask 077
mysqldump --defaults-extra-file=/etc/mysql/debian.cnf --single-transaction --events --skip-dump-date --routines --opt --triggers --all-databases > /var/backups/mysql-databases.sql 


